Add PWA requirements
bastislack/highline-freestyle pull request #299
Opened 2023-09-18 17:31 UTC by bastislack

Make the app an installable PWA.

2023-09-20 16:52 UTC, WaldemarLehner commented
Lighthouse PWA Report: 
![image](https://github.com/bastislack/highline-freestyle/assets/27686785/535844b8-18b0-42df-b8a6-9f4387638065)

Only thing thats marked as an issue here is that the [Manifest doesn't have a maskable icon](https://developer.chrome.com/docs/lighthouse/pwa/maskable-icon-audit/?utm_source=lighthouse&utm_medium=devtools)

Given that we don't have an icon configured yet, I wouldn't bother with this for now.

2023-09-20 16:53 UTC, WaldemarLehner approved these changes

2023-09-20 16:53 UTC, WaldemarLehner commented on public/logo96.png
Icon is not suitable for small screens. But that's an issue for later ;)

2023-09-20 17:03 UTC, WaldemarLehner requested changes

2023-09-20 17:03 UTC, WaldemarLehner commented on pnpm-lock.yaml
Actually… this shouldnt be here. We make use of package-lock.json — having 2 "sources of truth" will just make things break i.e. "it works on my machine" — we either use pnpm, or npm.

2023-09-23 13:24 UTC, bastislack commented on pnpm-lock.yaml
I read that pnpm is better than npm. Should we switch to using pnpm, or should we just stick to npm?

2023-09-23 14:14 UTC, WaldemarLehner commented on pnpm-lock.yaml
It's "better" in the sense that it makes use of centralized cache locally and just sym-links to that cache. 

**BUT** it also means that anyone that wants to work on the Repo *has* to use pnpm — which imo is not something we want.

I personally would like to stick with the default node package manager, npm :D

2023-10-26 17:14 UTC, merged